### ISSUE TITLE
deltaepsilon/angular-packery permission denied

### ISSUE THREAD

**Issue by yieme** [deltaepsilon/quiver-cms#25]
Was thinking about building a CMS on Firebase then came across Quiver. Sweet!

At the `bower install` step I get the following:

> bower ECMDERR       Failed to execute "git ls-remote --tags --heads git@github.com:deltaepsilon/angular-packery.git", exit code of #128 Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

Thoughts?

**Comment by deltaepsilon** [comment]
I'm moving away from Packery, so you can delete it from bower.json. I'm doing a
huge redesign, so the docs are our of date for the time being. I'm happy to help
you set it up if you like.
Chris.

On Fri, Apr 10, 2015 at 11:16 AM, deltaepsilon/quiver-cms
<reply@reply.github.com>
wrote:Was thinking about building a CMS on Firebase then came across Quiver. Sweet!

At the bower install step I get the following:

bower ECMDERR Failed to execute "git ls-remote --tags --heads git@github.com [git@github.com] :deltaepsilon/angular-packery.git", exit code of #128 Permission denied
(publickey). fatal: Could not read from remote repository. Please make sure you
have the correct access rights and the repository exists.

Thoughts?

**Comment by yieme** [comment]
Good deal. Thank you, Chris. I pulled packery and now I get the same issue with quiver-angular-utilities.

**Comment by yieme** [comment]
I changed ```bower.json``` to:

```js
{
  "name": "quiver-cms",
  "version": "0.1.5",
  "dependencies": {
    "angular": ">=1.3.13",
    "json3": "~3.2.6",
    "es5-shim": "~2.1.0",
    "quiver-angular-utilities": "*",
    "foundation": "~5.4.3",
    "font-awesome": "~4.2.0",
    "angular-markdown-editable": "~0.0.8",
    "angular-slugify": "~1.0.0",
    "restangular": "~1.4.0",
    "angular-ui-router": "~0.2.11",
    "angular-md5": "~0.1.7",
    "ngstorage": "~0.3.0",
    "ng-flow": "2",
    "angular-google-analytics": "*",
    "firebase": "~2.0.4",
    "angularfire": "~1.0.0",
    "angularfire-authentication": "*",
    "angular-sanitize": "~1.3.13",
    "angular-packery": "*",
    "angular-material": "~0.8.3",
    "materialize": "~0.96.0"
  },
  "devDependencies": {
    "angular": ">=1.3.13",
    "angular-mocks": ">=1.3.13",
    "angular-scenario": ">=1.3.13",
    "grunt-contrib-jasmine": "~0.8.1"
  },
  "resolutions": {
    "angular": ">=1.2.0",
    "angular-mocks": ">=1.3.0",
    "firebase": "2.2.x",
    "angularfire": "~1.0.0"
  }
}
```

These are the generic versions instead of the specific repo versions and I was able to get ```grunt build``` to run.

I was also able to get ```node content-server.js``` and ```node cms-server.js``` to run.

Now getting **Forbidden** accessing anything at ```http://localhost:9800/```.

Also ```http://localhost:9801/``` doesn't appear to be serving the **static/*** files.

Thoughts?

What do you think about moving cms-server into it's own project that could be served with a simple Express or static server like [harp](http://harpjs.com/)?

**Comment by deltaepsilon** [comment]
Hmmm. How do you have your Nginx set up? The Nginx settings for these servers are a little tricky. Here's how mine is configured.

```
server {
  listen 80;
  server_name dev.quiver.is 192.168.1.31;
  return 302 https://dev.quiver.is$request_uri;
}


server {
  listen	443;
  server_name dev.quiver.is 192.168.1.31;

  ssl on;
  ssl_certificate      /Users/quiver/SSL/STAR_quiver_is/quiver.crt;
  ssl_certificate_key  /Users/quiver/SSL/STAR_quiver_is/quiver_is.key;

  ssl_session_timeout 5m;

  ssl_protocols  SSLv2 SSLv3 TLSv1;
  ssl_ciphers  HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers   on;

  #rewrite_log on;

  location ~ ^/(app|images|lib|scripts|styles|views) {
    proxy_pass http://127.0.0.1:9800;
  }

  location ~ ^/api(/?)(.*) {
    proxy_set_header X-Real-IP  $remote_addr;
  	proxy_set_header X-Forwarded-For $remote_addr;
  	proxy_set_header Host $host;
  	proxy_pass http://127.0.0.1:9800/$2;
  }

  location / {
    proxy_set_header X-Real-IP  $remote_addr;
  	proxy_set_header X-Forwarded-For $remote_addr;
  	proxy_set_header Host $host;
  	proxy_pass http://127.0.0.1:9801;
  }


}


```

**Comment by deltaepsilon** [comment]
@yieme,

I've got a Dockerfile that you can use to get this running in a Docker container if you're familiar with that kind of stuff. Docker isn't the best for development, but I use it for all of my deploys.

I need to spend a day on the README to document my configuration process. I'm developing Quiver CMS to run calligraphy.org, which has yet to launch... so I'm spending every spare minute trying to get that project shipped. I'll clean up the current feature set, squash as many bugs as I can find and write a few more views in the next month.

This repo is a great starting point if you've got experience with Express, Firebase, Angular and Nginx. It's even better if you know some Docker. You'll want to aggressively pull my changes for the next couple of months as I refactor the front end. It's an ambitious project that some very specific calligraphy.org needs, and I'm developing it entirely on my own. It makes great sense to me... but I have no idea if the code is readable to anyone else.
