### ISSUE TITLE
no demo link

### ISSUE THREAD

**Issue by TimeTravelersHackMe** [deltaepsilon/quiver-cms#26]
Hi, I wasn't sure where to post this. Any chance you can supply us with a demo link?

**Comment by deltaepsilon** [comment]
Hmmm. I've been working on this for my own needs and not updating the README or paying much attention to the open-source nature of it.

I currently have an instance of Quiver-CMS running [Calligraphy.org](https://www.calligraphy.org). You're welcome to create an account there and poke around. You won't be able to see any of the moderator or admin portions of the site, but you'll get a good idea of what it looks like from a user's perspective.

I'm deploying with Docker, so my Dockerfile works. You may need to fuss around a bit with the config to get NGINX working, but once you've done that, I have launch scripts in /bin that will take you across the finish line.

**Comment by TimeTravelersHackMe** [comment]
Thank you! I love open source people.

I wish I had something to give back to the community like you do..
